"""Add environment field to endpoint_tests and test_results

Revision ID: 03b202c12609
Revises: a6581ed37f3b
Create Date: 2026-03-06 00:30:03.646921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03b202c12609'
down_revision: Union[str, None] = 'a6581ed37f3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoint_tests', sa.Column('environment', sa.String(length=50), nullable=False, server_default='dev'))
    op.add_column('test_results', sa.Column('environment', sa.String(length=50), nullable=False, server_default='dev'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_results', 'environment')
    op.drop_column('endpoint_tests', 'environment')
    # ### end Alembic commands ###
