"""Add test_batch table

Revision ID: 416f6f02fa03
Revises: 03b202c12609
Create Date: 2026-03-08 21:44:13.232537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '416f6f02fa03'
down_revision: Union[str, None] = '03b202c12609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 清理现有测试结果数据
    from sqlalchemy import text
    conn = op.get_bind()
    conn.execute(text("DELETE FROM test_results"))
    
    # 创建 test_batches 表
    op.create_table('test_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=50), nullable=False),
    sa.Column('system_id', sa.String(length=36), nullable=True),
    sa.Column('api_id', sa.String(length=36), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('pass_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['apis.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_batches_batch_id'), 'test_batches', ['batch_id'], unique=True)
    op.alter_column('test_results', 'batch_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_foreign_key(None, 'test_results', 'test_batches', ['batch_id'], ['batch_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_results', type_='foreignkey')
    op.alter_column('test_results', 'batch_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_test_batches_batch_id'), table_name='test_batches')
    op.drop_table('test_batches')
    # ### end Alembic commands ###
