"""Remove endpoint_id field from health_check_results

Revision ID: 87d34c64b5b7
Revises: ba46b671fa26
Create Date: 2026-02-14 10:49:21.792959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87d34c64b5b7'
down_revision: Union[str, None] = 'ba46b671fa26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('health_check_results_endpoint_id_fkey', 'health_check_results', type_='foreignkey')
    op.drop_column('health_check_results', 'endpoint_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_check_results', sa.Column('endpoint_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.create_foreign_key('health_check_results_endpoint_id_fkey', 'health_check_results', 'endpoints', ['endpoint_id'], ['id'])
    # ### end Alembic commands ###
