"""Add request_url and request_details fields to health_check_results

Revision ID: ab96b08eda0b
Revises: 5c4dd0dc2a8b
Create Date: 2026-02-14 10:13:14.038298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab96b08eda0b'
down_revision: Union[str, None] = '5c4dd0dc2a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_check_results', sa.Column('request_url', sa.Text(), nullable=True))
    op.add_column('health_check_results', sa.Column('request_details', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('health_check_results', 'request_details')
    op.drop_column('health_check_results', 'request_url')
    # ### end Alembic commands ###
