"""Add http_method field to TestResult

Revision ID: f9876d99d5cf
Revises: 8f7c9e6d1a2b
Create Date: 2026-03-10 00:46:45.832402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9876d99d5cf'
down_revision: Union[str, None] = '8f7c9e6d1a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_batches', 'system_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.add_column('test_results', sa.Column('http_method', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_results', 'http_method')
    op.alter_column('test_batches', 'system_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###
